"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "vi"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Auth
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.fullName": "Full Name",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.signUp": "Sign up",
    "auth.signIn": "Sign in",
    "auth.logout": "Logout",
    "auth.resetPassword": "Reset Password",
    "auth.newPassword": "New Password",
    "auth.verifyEmail": "Verify Email",
    "auth.twoFactorAuth": "Two-Factor Authentication",
    "auth.enterCode": "Enter verification code",
    "auth.loginSuccess": "Login successful",
    "auth.verificationEmailSent": "Verification email sent successfully",
    "auth.resendError": "Failed to resend verification email",
    "auth.emailVerifiedSuccess": "Email verified successfully",
    "auth.verificationError": "Email verification failed",

    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.tickets": "Tickets",
    "nav.profile": "Profile",
    "nav.knowledgeBase": "Knowledge Base",
    "knowledge.description": "Search and read documentation",
    "knowledge.searchPlaceholder": "Search documents...",
    "knowledge.allCategories": "All categories",
    "knowledge.found": "Found",
    "knowledge.documents": "documents",
    "knowledge.noDocuments": "No documents found",
    "knowledge.noDocumentsDescription": "No documents match your search",
    "knowledge.readMore": "Read more",
    "knowledge.download": "Download",
    "knowledge.noFile": "No file attached",
    "knowledge.documentNotFound": "Document not found",
    "knowledge.documentNotFoundDescription": "The document you are looking for does not exist or has been removed",
    "knowledge.backToList": "Back to list",
    "knowledge.views": "views",
    "knowledge.preview": "Preview",
    "knowledge.videoNotSupported": "Your browser does not support this video",
    "knowledge.downloadError": "Cannot download file",

    "nav.notifications": "Notifications",
    "nav.users": "Users",
    "nav.settings": "Settings",
    "nav.reports": "Reports",

    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.totalTickets": "Total Tickets",
    "dashboard.newTickets": "New Tickets",
    "dashboard.openTickets": "Open Tickets",
    "dashboard.resolvedTickets": "Resolved Tickets",
    "dashboard.pendingTickets": "Pending Tickets",
    "dashboard.recentTickets": "Recent Tickets",
    "dashboard.createNewTicket": "Create New Ticket",
    "dashboard.overview": "Here's an overview of your support tickets",

    // Tickets
    "tickets.title": "Title",
    "tickets.status": "Status",
    "tickets.priority": "Priority",
    "tickets.category": "Category",
    "tickets.assignedTo": "Assigned To",
    "tickets.createdAt": "Created At",
    "tickets.updatedAt": "Updated At",
    "tickets.description": "Description",
    "tickets.attachments": "Attachments",
    "tickets.comments": "Comments",
    "tickets.addComment": "Add Comment",
    "tickets.updateTicket": "Update Ticket",
    "tickets.deleteTicket": "Delete Ticket",
    "tickets.newTicket": "New Ticket",
    "tickets.details": "Ticket Details",
    "tickets.completeInfo": "Complete information about this support request",
    "tickets.category": "Category",
    "tickets.productType": "Product Type",
    "tickets.created": "Created",
    "tickets.resolved": "Resolved",
    "tickets.attachment": "Attachment",
    "tickets.view": "View",
    "tickets.download": "Download",
    "tickets.addCommentPlaceholder": "Add a comment...",
    "tickets.sendComment": "Send Comment",
    "tickets.sending": "Sending...",
    "tickets.reply": "Reply",
    "tickets.noComments": "No comments yet",
    "tickets.viewAttachment": "View Attachment",
    "tickets.backToTickets": "Back to Tickets",
    "tickets.ticketNotFound": "Ticket not found",
    "tickets.edit": "Edit",
    "tickets.delete": "Delete",
    "tickets.confirmDelete": "Are you sure you want to delete this ticket?",
    "tickets.editTitle": "Edit Ticket",
    "tickets.editDescription": "Update ticket information",
    "tickets.ticketInfo": "Ticket Information",
    "tickets.updateTicketInfo": "Update ticket support information",
    "tickets.title": "Title",
    "tickets.titlePlaceholder": "Enter ticket title",
    "tickets.descriptionPlaceholder": "Describe your issue in detail",
    "tickets.selectCategory": "Select category",
    "tickets.selectProductType": "Select product type",
    "tickets.selectPriority": "Select priority",
    "tickets.cancel": "Cancel",
    "tickets.saveChanges": "Save Changes",
    "tickets.saving": "Saving...",
    "tickets.fillAllFields": "Please fill in all information",
    "tickets.updateSuccess": "Ticket updated successfully",
    "tickets.updateError": "Cannot update ticket",
    "tickets.onlyNewStatus": "Can only edit tickets with 'New' status",
    "tickets.withdraw": "Withdraw",
    "tickets.confirmWithdraw": "Are you sure you want to withdraw this ticket?",
    "tickets.withdrawSuccess": "Ticket withdrawn successfully",
    "tickets.withdrawError": "Cannot withdraw ticket",
    "tickets.downloadError": "Cannot download file",
    "tickets.createTitle": "Create New Support Ticket",
    "tickets.createTicket": "Create Ticket",
    "tickets.creating": "Creating...",
    "tickets.createSuccess": "Ticket created successfully",
    "tickets.createError": "Cannot create ticket",
    "tickets.fileTooLarge": "File too large (max 10MB)",
    "tickets.createDescription": "Create a new support request for us",
    "tickets.loadingForm": "Loading form...",
    "tickets.showing": "Showing",
    "tickets.of": "of",
    "tickets.tickets": "tickets",
    "tickets.yourTickets": "Your Tickets",
    "tickets.allSupportRequests": "All your support requests",
    "tickets.displaying": "Displaying",
    "tickets.total": "Total",
    "tickets.page": "Page",
    "tickets.manageRequests": "Manage your support requests",
    "tickets.latestRequests": "Your latest support requests",

    // Profile
    "profile.title": "Profile",
    "profile.description": "Manage your personal information and security",
    "profile.personalInfo": "Personal Information",
    "profile.security": "Security",
    "profile.name": "Full Name",
    "profile.namePlaceholder": "Enter your full name",
    "profile.phone": "Phone Number",
    "profile.phonePlaceholder": "Enter your phone number",
    "profile.email": "Email",
    "profile.emailPlaceholder": "Enter your email",
    "profile.emailVerified": "Email Verified",
    "profile.emailNotVerified": "Email not verified",
    "profile.verifyEmail": "Verify Email",
    "profile.verifyNow": "Verify Now",
    "profile.sending": "Sending...",
    "profile.verifying": "Verifying...",
    "profile.saveChanges": "Save Changes",
    "profile.saving": "Saving...",
    "profile.updateSuccess": "Profile updated successfully",
    "profile.updateError": "Cannot update profile",
    "profile.fillRequiredFields": "Please fill in all required fields",
    "profile.changePassword": "Change Password",
    "profile.oldPassword": "Old Password",
    "profile.oldPasswordPlaceholder": "Enter your old password",
    "profile.newPassword": "New Password",
    "profile.newPasswordPlaceholder": "Enter your new password",
    "profile.confirmPassword": "Confirm Password",
    "profile.confirmPasswordPlaceholder": "Confirm your new password",
    "profile.changing": "Changing...",
    "profile.passwordChangeSuccess": "Password changed successfully",
    "profile.passwordChangeError": "Cannot change password",
    "profile.fillAllPasswordFields": "Please fill in all password fields",
    "profile.passwordsDoNotMatch": "Passwords do not match",
    "profile.passwordTooShort": "Password must be at least 6 characters",
    "profile.twoFactorAuth": "Two-Factor Authentication",
    "profile.twoFactorEnabled": "Two-factor authentication is enabled",
    "profile.twoFactorDisabled": "Two-factor authentication is disabled",
    "profile.setup2FA": "Setup 2FA",
    "profile.disable2FA": "Disable 2FA",
    "profile.enable2FA": "Enable 2FA",
    "profile.scanQRCode": "Scan QR code with authenticator app",
    "profile.secretKey": "Secret Key",
    "profile.secretKeyDescription": "Save this key in a safe place to recover 2FA",
    "profile.nextStep": "Next Step",
    "profile.enter2FACode": "Enter 6-digit verification code",
    "profile.verifying": "Verifying...",
    "profile.enable2FASuccess": "Two-factor authentication enabled successfully",
    "profile.enable2FAError": "Cannot enable two-factor authentication",
    "profile.disable2FASuccess": "Two-factor authentication disabled successfully",
    "profile.disable2FAError": "Cannot disable two-factor authentication",
    "profile.setup2FAError": "Cannot setup 2FA",
    "profile.settingUp": "Setting up...",

    // Status
    "status.new": "New",
    "status.inProgress": "In Progress",
    "status.pending": "Pending",
    "status.resolved": "Resolved",
    "status.closed": "Closed",

    // Priority
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "priority.urgent": "Urgent",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.loading": "Loading...",
    "common.noData": "No data available",
    "common.error": "An error occurred",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.viewAll": "View All",
          "system.name": "Support System",
      // Admin Dashboard
      "admin.dashboard.title": "Admin Dashboard",
      "admin.dashboard.description": "Overview of system performance and statistics",
      "admin.dashboard.totalTickets": "Total Tickets",
      "admin.dashboard.processingTickets": "Processing Tickets",
      "admin.dashboard.avgProcessingTime": "Avg Processing Time",
      "admin.dashboard.resolutionRate": "Resolution Rate",
      "admin.dashboard.allTime": "All time",
      "admin.dashboard.currentlyProcessing": "Currently processing",
      "admin.dashboard.averageTime": "Average time",
      "admin.dashboard.thisMonth": "This month",
      "admin.dashboard.statusDistribution": "Status Distribution",
      "admin.dashboard.ticketStatusBreakdown": "Breakdown of tickets by status",
      "admin.dashboard.topStaff": "Top Staff",
      "admin.dashboard.bestPerformers": "Best performing staff this month",
      "admin.dashboard.tickets": "tickets",
      "admin.dashboard.avg": "avg",
      "admin.dashboard.monthlyStats": "Monthly Statistics",
      "admin.dashboard.currentMonthPerformance": "Current month performance overview",
      "admin.dashboard.newTickets": "New Tickets",
      "admin.dashboard.resolvedTickets": "Resolved Tickets",
      "admin.dashboard.pendingTickets": "Pending Tickets",
      "admin.dashboard.noStaffData": "No staff performance data available",
    "notifications.title": "Notifications",
    "notifications.viewAll": "View All",
    "notifications.noNotifications": "No notifications",
    "notifications.markAsRead": "Mark as read",
    "notifications.markAllAsRead": "Mark all as read",
    "notifications.unread": "unread",
    "notifications.notifications": "notifications",
    "notifications.viewTicket": "View Ticket",
    "notifications.type.newTicket": "New Ticket",
    "notifications.type.ticketComment": "Ticket Comment",
    "notifications.type.ticketUpdate": "Ticket Update",
    "notifications.type.ticketDeleted": "Ticket Deleted",
    "notifications.type.notification": "Notification",
  },
  vi: {
    // Auth
    "auth.login": "Đăng nhập",
    "auth.register": "Đăng ký",
    "auth.email": "Email",
    "auth.password": "Mật khẩu",
    "auth.confirmPassword": "Xác nhận mật khẩu",
    "auth.fullName": "Họ và tên",
    "auth.rememberMe": "Ghi nhớ đăng nhập",
    "auth.forgotPassword": "Quên mật khẩu?",
    "auth.dontHaveAccount": "Chưa có tài khoản?",
    "auth.alreadyHaveAccount": "Đã có tài khoản?",
    "auth.signUp": "Đăng ký",
    "auth.signIn": "Đăng nhập",
    "auth.logout": "Đăng xuất",
    "auth.resetPassword": "Đặt lại mật khẩu",
    "auth.newPassword": "Mật khẩu mới",
    "auth.verifyEmail": "Xác minh Email",
    "auth.twoFactorAuth": "Xác thực hai yếu tố",
    "auth.enterCode": "Nhập mã xác minh",
    "auth.loginSuccess": "Đăng nhập thành công",
    "auth.verificationEmailSent": "Đã gửi email xác thực thành công",
    "auth.resendError": "Không thể gửi lại email xác thực",
    "auth.emailVerifiedSuccess": "Xác thực email thành công",
    "auth.verificationError": "Xác thực email thất bại",

    // Navigation
    "nav.dashboard": "Bảng điều khiển",
    "nav.tickets": "Yêu cầu hỗ trợ",
    "nav.profile": "Hồ sơ",
    "nav.knowledgeBase": "Kho tài liệu",
    "nav.notifications": "Thông báo",
    "nav.users": "Người dùng",
    "nav.settings": "Cài đặt",
    "nav.reports": "Báo cáo",

    // Dashboard
    "dashboard.welcome": "Chào mừng trở lại",
    "dashboard.totalTickets": "Tổng số yêu cầu",
    "dashboard.newTickets": "Yêu cầu mới",
    "dashboard.openTickets": "Yêu cầu đang mở",
    "dashboard.resolvedTickets": "Yêu cầu đã giải quyết",
    "dashboard.pendingTickets": "Yêu cầu chờ xử lý",
    "dashboard.recentTickets": "Yêu cầu gần đây",
    "dashboard.createNewTicket": "Tạo yêu cầu mới",
    "dashboard.overview": "Đây là tổng quan về các yêu cầu hỗ trợ của bạn",

    // Tickets
    "tickets.title": "Tiêu đề",
    "tickets.status": "Trạng thái",
    "tickets.priority": "Mức độ ưu tiên",
    "tickets.category": "Danh mục",
    "tickets.assignedTo": "Được gán cho",
    "tickets.createdAt": "Ngày tạo",
    "tickets.updatedAt": "Cập nhật cuối",
    "tickets.description": "Mô tả",
    "tickets.attachments": "Tệp đính kèm",
    "tickets.comments": "Bình luận",
    "tickets.addComment": "Thêm bình luận",
    "tickets.updateTicket": "Cập nhật yêu cầu",
    "tickets.deleteTicket": "Xóa yêu cầu",
    "tickets.newTicket": "Yêu cầu mới",
    "tickets.details": "Chi tiết yêu cầu",
    "tickets.completeInfo": "Thông tin đầy đủ về yêu cầu hỗ trợ này",
    "tickets.description": "Mô tả",
    "tickets.category": "Danh mục",
    "tickets.productType": "Loại sản phẩm",
    "tickets.created": "Ngày tạo",
    "tickets.resolved": "Ngày giải quyết",
    "tickets.attachment": "Tệp đính kèm",
    "tickets.view": "Xem",
    "tickets.download": "Tải xuống",
    "tickets.comments": "Bình luận",
    "tickets.addComment": "Thêm bình luận",
    "tickets.addCommentPlaceholder": "Thêm bình luận...",
    "tickets.sendComment": "Gửi bình luận",
    "tickets.sending": "Đang gửi...",
    "tickets.reply": "Trả lời",
    "tickets.noComments": "Chưa có bình luận nào",
    "tickets.viewAttachment": "Xem tệp đính kèm",
    "tickets.backToTickets": "Quay lại danh sách yêu cầu",
    "tickets.ticketNotFound": "Không tìm thấy yêu cầu",
    "tickets.edit": "Chỉnh sửa",
    "tickets.delete": "Xóa",
    "tickets.confirmDelete": "Bạn có chắc chắn muốn xóa yêu cầu này?",
    "tickets.editTitle": "Chỉnh sửa yêu cầu",
    "tickets.editDescription": "Cập nhật thông tin yêu cầu",
    "tickets.ticketInfo": "Thông tin yêu cầu",
    "tickets.updateTicketInfo": "Cập nhật thông tin yêu cầu hỗ trợ",
    "tickets.title": "Tiêu đề",
    "tickets.titlePlaceholder": "Nhập tiêu đề yêu cầu",
    "tickets.descriptionPlaceholder": "Mô tả chi tiết vấn đề của bạn",
    "tickets.selectCategory": "Chọn danh mục",
    "tickets.selectProductType": "Chọn loại sản phẩm",
    "tickets.selectPriority": "Chọn mức độ ưu tiên",
    "tickets.cancel": "Hủy",
    "tickets.saveChanges": "Lưu thay đổi",
    "tickets.saving": "Đang lưu...",
    "tickets.fillAllFields": "Vui lòng điền đầy đủ thông tin",
    "tickets.updateSuccess": "Yêu cầu đã được cập nhật thành công",
    "tickets.updateError": "Không thể cập nhật yêu cầu",
    "tickets.onlyNewStatus": "Chỉ có thể chỉnh sửa yêu cầu khi trạng thái là 'Mới'",
    "tickets.withdraw": "Thu hồi",
    "tickets.confirmWithdraw": "Bạn có chắc chắn muốn thu hồi yêu cầu này?",
    "tickets.withdrawSuccess": "Yêu cầu đã được thu hồi thành công",
    "tickets.withdrawError": "Không thể thu hồi yêu cầu",
    "tickets.downloadError": "Không thể tải xuống file",
    "tickets.createTitle": "Tạo yêu cầu hỗ trợ mới",
    "tickets.createTicket": "Tạo yêu cầu",
    "tickets.creating": "Đang tạo...",

    // Knowledge Base
    "knowledge.description": "Tìm kiếm và đọc tài liệu hướng dẫn",
    "knowledge.searchPlaceholder": "Tìm kiếm tài liệu...",
    "knowledge.allCategories": "Tất cả danh mục",
    "knowledge.found": "Tìm thấy",
    "knowledge.documents": "tài liệu",
    "knowledge.noDocuments": "Không tìm thấy tài liệu",
    "knowledge.noDocumentsDescription": "Không có tài liệu nào phù hợp với tìm kiếm của bạn",
    "knowledge.readMore": "Đọc thêm",
    "knowledge.download": "Tải xuống",
    "knowledge.noFile": "Không có file đính kèm",
    "knowledge.documentNotFound": "Không tìm thấy tài liệu",
    "knowledge.documentNotFoundDescription": "Tài liệu bạn đang tìm kiếm không tồn tại hoặc đã bị xóa",
    "knowledge.backToList": "Quay lại danh sách",
    "knowledge.views": "lượt xem",
    "knowledge.preview": "Xem trước",
    "knowledge.videoNotSupported": "Trình duyệt không hỗ trợ video này",
    "knowledge.downloadError": "Không thể tải xuống file",
    "tickets.createSuccess": "Yêu cầu đã được tạo thành công",
    "tickets.createError": "Không thể tạo yêu cầu",
    "tickets.fileTooLarge": "File quá lớn (tối đa 10MB)",
    "tickets.attachment": "Tệp đính kèm",
    "tickets.createDescription": "Tạo yêu cầu hỗ trợ mới cho chúng tôi",
    "tickets.loadingForm": "Đang tải form...",
    "tickets.showing": "Hiển thị",
    "tickets.of": "trong tổng số",
    "tickets.tickets": "tickets",
    "tickets.yourTickets": "Yêu cầu của bạn",
    "tickets.allSupportRequests": "Tất cả yêu cầu hỗ trợ của bạn",
    "tickets.displaying": "Hiển thị",
    "tickets.total": "Tổng",
    "tickets.page": "Trang",
    "tickets.manageRequests": "Quản lý yêu cầu hỗ trợ của bạn",
    "tickets.latestRequests": "Yêu cầu hỗ trợ gần đây của bạn",

    // Profile
    "profile.title": "Hồ sơ",
    "profile.description": "Quản lý thông tin cá nhân và bảo mật",
    "profile.personalInfo": "Thông tin cá nhân",
    "profile.security": "Bảo mật",
    "profile.name": "Họ và tên",
    "profile.namePlaceholder": "Nhập họ và tên",
    "profile.phone": "Số điện thoại",
    "profile.phonePlaceholder": "Nhập số điện thoại",
    "profile.email": "Email",
    "profile.emailPlaceholder": "Nhập email",
    "profile.emailVerified": "Email đã xác thực",
    "profile.emailNotVerified": "Email chưa xác thực",
    "profile.verifyEmail": "Xác thực email",
    "profile.verifyNow": "Xác thực ngay",
    "profile.sending": "Đang gửi...",
    "profile.verifying": "Đang xác thực...",
    "profile.saveChanges": "Lưu thay đổi",
    "profile.saving": "Đang lưu...",
    "profile.updateSuccess": "Cập nhật thông tin thành công",
    "profile.updateError": "Không thể cập nhật thông tin",
    "profile.fillRequiredFields": "Vui lòng điền đầy đủ thông tin bắt buộc",
    "profile.changePassword": "Đổi mật khẩu",
    "profile.oldPassword": "Mật khẩu cũ",
    "profile.oldPasswordPlaceholder": "Nhập mật khẩu cũ",
    "profile.newPassword": "Mật khẩu mới",
    "profile.newPasswordPlaceholder": "Nhập mật khẩu mới",
    "profile.confirmPassword": "Xác nhận mật khẩu",
    "profile.confirmPasswordPlaceholder": "Nhập lại mật khẩu mới",
    "profile.changing": "Đang đổi...",
    "profile.passwordChangeSuccess": "Đổi mật khẩu thành công",
    "profile.passwordChangeError": "Không thể đổi mật khẩu",
    "profile.fillAllPasswordFields": "Vui lòng điền đầy đủ thông tin mật khẩu",
    "profile.passwordsDoNotMatch": "Mật khẩu xác nhận không khớp",
    "profile.passwordTooShort": "Mật khẩu phải có ít nhất 6 ký tự",
    "profile.twoFactorAuth": "Xác thực hai yếu tố",
    "profile.twoFactorEnabled": "Đã bật xác thực hai yếu tố",
    "profile.twoFactorDisabled": "Chưa bật xác thực hai yếu tố",
    "profile.setup2FA": "Thiết lập 2FA",
    "profile.disable2FA": "Tắt 2FA",
    "profile.enable2FA": "Bật 2FA",
    "profile.scanQRCode": "Quét mã QR bằng ứng dụng xác thực",
    "profile.secretKey": "Khóa bí mật",
    "profile.secretKeyDescription": "Lưu khóa này ở nơi an toàn để khôi phục 2FA",
    "profile.nextStep": "Bước tiếp theo",
    "profile.enter2FACode": "Nhập mã xác thực 6 số",
    "profile.verifying": "Đang xác thực...",
    "profile.enable2FASuccess": "Bật xác thực hai yếu tố thành công",
    "profile.enable2FAError": "Không thể bật xác thực hai yếu tố",
    "profile.disable2FASuccess": "Tắt xác thực hai yếu tố thành công",
    "profile.disable2FAError": "Không thể tắt xác thực hai yếu tố",
    "profile.setup2FAError": "Không thể thiết lập 2FA",
    "profile.settingUp": "Đang thiết lập...",

    // Status
    "status.new": "Mới",
    "status.inProgress": "Đang xử lý",
    "status.pending": "Chờ phản hồi",
    "status.resolved": "Đã giải quyết",
    "status.closed": "Đã đóng",

    // Priority
    "priority.low": "Thấp",
    "priority.medium": "Trung bình",
    "priority.high": "Cao",
    "priority.urgent": "Khẩn cấp",

    // Common
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.delete": "Xóa",
    "common.edit": "Sửa",
    "common.view": "Xem",
    "common.search": "Tìm kiếm",
    "common.filter": "Lọc",
    "common.loading": "Đang tải...",
    "common.noData": "Không có dữ liệu",
    "common.error": "Đã xảy ra lỗi",
    "common.success": "Thành công",
    "common.confirm": "Xác nhận",
    "common.back": "Quay lại",
    "common.next": "Tiếp theo",
    "common.previous": "Trước",
    "common.submit": "Gửi",
    "common.close": "Đóng",
    "common.viewAll": "Xem tất cả",
          "system.name": "Hệ Thống Hỗ Trợ",
      // Admin Dashboard
      "admin.dashboard.title": "Bảng Điều Khiển Admin",
      "admin.dashboard.description": "Tổng quan hiệu suất và thống kê hệ thống",
      "admin.dashboard.totalTickets": "Tổng Số Ticket",
      "admin.dashboard.processingTickets": "Ticket Đang Xử Lý",
      "admin.dashboard.avgProcessingTime": "Thời Gian Xử Lý TB",
      "admin.dashboard.resolutionRate": "Tỷ Lệ Giải Quyết",
      "admin.dashboard.allTime": "Tất cả thời gian",
      "admin.dashboard.currentlyProcessing": "Đang xử lý",
      "admin.dashboard.averageTime": "Thời gian trung bình",
      "admin.dashboard.thisMonth": "Tháng này",
      "admin.dashboard.statusDistribution": "Phân Bố Trạng Thái",
      "admin.dashboard.ticketStatusBreakdown": "Phân tích ticket theo trạng thái",
      "admin.dashboard.topStaff": "Nhân Viên Xuất Sắc",
      "admin.dashboard.bestPerformers": "Nhân viên hiệu suất cao nhất tháng này",
      "admin.dashboard.tickets": "ticket",
      "admin.dashboard.avg": "tb",
      "admin.dashboard.monthlyStats": "Thống Kê Tháng",
      "admin.dashboard.currentMonthPerformance": "Tổng quan hiệu suất tháng hiện tại",
      "admin.dashboard.newTickets": "Ticket Mới",
      "admin.dashboard.resolvedTickets": "Ticket Đã Giải Quyết",
      "admin.dashboard.pendingTickets": "Ticket Chờ Xử Lý",
      "admin.dashboard.noStaffData": "Không có dữ liệu hiệu suất nhân viên",
    "notifications.title": "Thông báo",
    "notifications.viewAll": "Xem tất cả",
    "notifications.noNotifications": "Không có thông báo",
    "notifications.markAsRead": "Đánh dấu đã đọc",
    "notifications.markAllAsRead": "Đánh dấu tất cả đã đọc",
    "notifications.unread": "chưa đọc",
    "notifications.notifications": "thông báo",
    "notifications.viewTicket": "Xem Ticket",
    "notifications.type.newTicket": "Ticket Mới",
    "notifications.type.ticketComment": "Bình Luận Ticket",
    "notifications.type.ticketUpdate": "Cập Nhật Ticket",
    "notifications.type.ticketDeleted": "Ticket Đã Xóa",
    "notifications.type.notification": "Thông Báo",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "vi")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
